CREATE TABLE [dbo].[DET_HISTORIA_MEDICA]
(
	[idDetHistoriaMedica] INT ,
	[idMedico] int,
	[idRecetaMedica] int,
	[idTratamiento] int,
	[idCita] int,
	[idAsistente] int,
	CONSTRAINT [PK_DET_HISTORIA_MEDICA] PRIMARY KEY CLUSTERED ([idDetHistoriaMedica] ASC), 
    CONSTRAINT [FK_DET_HISTORIA_MEDICA_CAB_MEDICO] FOREIGN KEY ([idMedico]) REFERENCES [CAB_MEDICO]([idMedico]), 
    CONSTRAINT [FK_DET_HISTORIA_MEDICA_CAB_RECETA_MEDICA] FOREIGN KEY ([idRecetaMedica]) REFERENCES [CAB_RECETA_MEDICA]([idRecetaMedica]), 
    CONSTRAINT [FK_DET_HISTORIA_MEDICA_TRATAMIENTO] FOREIGN KEY ([idTratamiento]) REFERENCES [TRATAMIENTO]([idTratamiento]), 
    CONSTRAINT [FK_DET_HISTORIA_MEDICA_CITA] FOREIGN KEY ([idCita]) REFERENCES [CITA]([idCita]), 
    CONSTRAINT [FK_DET_HISTORIA_MEDICA_PERSONAL_ADM] FOREIGN KEY ([idAsistente]) REFERENCES [PERSONAL_ADM]([idAsistente]),
)
